function Dwater=CubeFastInterpolation(Water,CubeDispl)
%% Input just for testing

QPw = Water; % (Nb water ; [x y z])

% Build interpolation matrix once 
N = 0.125*[(1-QPw(:,1)).*(1-QPw(:,2)).*(1-QPw(:,3)), ....
           (1+QPw(:,1)).*(1-QPw(:,2)).*(1-QPw(:,3)), ....
           (1+QPw(:,1)).*(1+QPw(:,2)).*(1-QPw(:,3)), ....
           (1-QPw(:,1)).*(1+QPw(:,2)).*(1-QPw(:,3)), ....
           (1-QPw(:,1)).*(1-QPw(:,2)).*(1+QPw(:,3)), ....
           (1+QPw(:,1)).*(1-QPw(:,2)).*(1+QPw(:,3)), ....
           (1+QPw(:,1)).*(1+QPw(:,2)).*(1+QPw(:,3)), ....
           (1-QPw(:,1)).*(1+QPw(:,2)).*(1+QPw(:,3))];
       
% Interpolated displacements
Dwater(:,1,:) = N * squeeze(CubeDispl(:,1,:));
Dwater(:,2,:) = N * squeeze(CubeDispl(:,2,:));
Dwater(:,3,:) = N * squeeze(CubeDispl(:,3,:));


end